/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedStrategiaRouteImport } from './routes/_authenticated/strategia'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSentimentRouteImport } from './routes/_authenticated/sentiment'
import { Route as AuthenticatedPositionsRouteImport } from './routes/_authenticated/positions'
import { Route as AuthenticatedModeRouteImport } from './routes/_authenticated/mode'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDiagnosticaRouteImport } from './routes/_authenticated/diagnostica'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBilancioRouteImport } from './routes/_authenticated/bilancio'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as ApiPublicHooksAiStrategySupervisorRouteImport } from './routes/api/public/hooks/ai-strategy-supervisor'
import { Route as ApiPublicCronTaxRemindersRouteImport } from './routes/api/public/cron/tax-reminders'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStrategiaRoute = AuthenticatedStrategiaRouteImport.update({
  id: '/strategia',
  path: '/strategia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSentimentRoute = AuthenticatedSentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPositionsRoute = AuthenticatedPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModeRoute = AuthenticatedModeRouteImport.update({
  id: '/mode',
  path: '/mode',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticaRoute =
  AuthenticatedDiagnosticaRouteImport.update({
    id: '/diagnostica',
    path: '/diagnostica',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBilancioRoute = AuthenticatedBilancioRouteImport.update({
  id: '/bilancio',
  path: '/bilancio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksAiStrategySupervisorRoute =
  ApiPublicHooksAiStrategySupervisorRouteImport.update({
    id: '/api/public/hooks/ai-strategy-supervisor',
    path: '/api/public/hooks/ai-strategy-supervisor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronTaxRemindersRoute =
  ApiPublicCronTaxRemindersRouteImport.update({
    id: '/api/public/cron/tax-reminders',
    path: '/api/public/cron/tax-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/bilancio': typeof AuthenticatedBilancioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostica': typeof AuthenticatedDiagnosticaRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/mode': typeof AuthenticatedModeRoute
  '/positions': typeof AuthenticatedPositionsRoute
  '/sentiment': typeof AuthenticatedSentimentRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/strategia': typeof AuthenticatedStrategiaRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/cron/tax-reminders': typeof ApiPublicCronTaxRemindersRoute
  '/api/public/hooks/ai-strategy-supervisor': typeof ApiPublicHooksAiStrategySupervisorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/bilancio': typeof AuthenticatedBilancioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostica': typeof AuthenticatedDiagnosticaRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/mode': typeof AuthenticatedModeRoute
  '/positions': typeof AuthenticatedPositionsRoute
  '/sentiment': typeof AuthenticatedSentimentRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/strategia': typeof AuthenticatedStrategiaRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/cron/tax-reminders': typeof ApiPublicCronTaxRemindersRoute
  '/api/public/hooks/ai-strategy-supervisor': typeof ApiPublicHooksAiStrategySupervisorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/bilancio': typeof AuthenticatedBilancioRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnostica': typeof AuthenticatedDiagnosticaRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/mode': typeof AuthenticatedModeRoute
  '/_authenticated/positions': typeof AuthenticatedPositionsRoute
  '/_authenticated/sentiment': typeof AuthenticatedSentimentRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/strategia': typeof AuthenticatedStrategiaRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/cron/tax-reminders': typeof ApiPublicCronTaxRemindersRoute
  '/api/public/hooks/ai-strategy-supervisor': typeof ApiPublicHooksAiStrategySupervisorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assistant'
    | '/bilancio'
    | '/dashboard'
    | '/diagnostica'
    | '/history'
    | '/logs'
    | '/mode'
    | '/positions'
    | '/sentiment'
    | '/settings'
    | '/strategia'
    | '/api/chat'
    | '/api/public/cron/tax-reminders'
    | '/api/public/hooks/ai-strategy-supervisor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/assistant'
    | '/bilancio'
    | '/dashboard'
    | '/diagnostica'
    | '/history'
    | '/logs'
    | '/mode'
    | '/positions'
    | '/sentiment'
    | '/settings'
    | '/strategia'
    | '/api/chat'
    | '/api/public/cron/tax-reminders'
    | '/api/public/hooks/ai-strategy-supervisor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assistant'
    | '/_authenticated/bilancio'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnostica'
    | '/_authenticated/history'
    | '/_authenticated/logs'
    | '/_authenticated/mode'
    | '/_authenticated/positions'
    | '/_authenticated/sentiment'
    | '/_authenticated/settings'
    | '/_authenticated/strategia'
    | '/api/chat'
    | '/api/public/cron/tax-reminders'
    | '/api/public/hooks/ai-strategy-supervisor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicCronTaxRemindersRoute: typeof ApiPublicCronTaxRemindersRoute
  ApiPublicHooksAiStrategySupervisorRoute: typeof ApiPublicHooksAiStrategySupervisorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/strategia': {
      id: '/_authenticated/strategia'
      path: '/strategia'
      fullPath: '/strategia'
      preLoaderRoute: typeof AuthenticatedStrategiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sentiment': {
      id: '/_authenticated/sentiment'
      path: '/sentiment'
      fullPath: '/sentiment'
      preLoaderRoute: typeof AuthenticatedSentimentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/positions': {
      id: '/_authenticated/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AuthenticatedPositionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mode': {
      id: '/_authenticated/mode'
      path: '/mode'
      fullPath: '/mode'
      preLoaderRoute: typeof AuthenticatedModeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostica': {
      id: '/_authenticated/diagnostica'
      path: '/diagnostica'
      fullPath: '/diagnostica'
      preLoaderRoute: typeof AuthenticatedDiagnosticaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bilancio': {
      id: '/_authenticated/bilancio'
      path: '/bilancio'
      fullPath: '/bilancio'
      preLoaderRoute: typeof AuthenticatedBilancioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/ai-strategy-supervisor': {
      id: '/api/public/hooks/ai-strategy-supervisor'
      path: '/api/public/hooks/ai-strategy-supervisor'
      fullPath: '/api/public/hooks/ai-strategy-supervisor'
      preLoaderRoute: typeof ApiPublicHooksAiStrategySupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/tax-reminders': {
      id: '/api/public/cron/tax-reminders'
      path: '/api/public/cron/tax-reminders'
      fullPath: '/api/public/cron/tax-reminders'
      preLoaderRoute: typeof ApiPublicCronTaxRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedBilancioRoute: typeof AuthenticatedBilancioRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosticaRoute: typeof AuthenticatedDiagnosticaRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedModeRoute: typeof AuthenticatedModeRoute
  AuthenticatedPositionsRoute: typeof AuthenticatedPositionsRoute
  AuthenticatedSentimentRoute: typeof AuthenticatedSentimentRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStrategiaRoute: typeof AuthenticatedStrategiaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedBilancioRoute: AuthenticatedBilancioRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosticaRoute: AuthenticatedDiagnosticaRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedModeRoute: AuthenticatedModeRoute,
  AuthenticatedPositionsRoute: AuthenticatedPositionsRoute,
  AuthenticatedSentimentRoute: AuthenticatedSentimentRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStrategiaRoute: AuthenticatedStrategiaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicCronTaxRemindersRoute: ApiPublicCronTaxRemindersRoute,
  ApiPublicHooksAiStrategySupervisorRoute:
    ApiPublicHooksAiStrategySupervisorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
